config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :lists do 
    resources :items
  end

  root 'lists#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    render layout: false
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.list }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item.list, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @item.list, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @item = Item.new
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    render layout: false
  end

  # def form
  #   render layout: false


  # end 
  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <% if @list.nil? %> 
    <div class="field">
      <%= f.label :list_id %><br>
      <%= f.text_field :list_id %> 
    </div>
  <% else %>
      <%= f.hidden_field :list_id, value: @list.id %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_list.html.erb
<% @list.items.each do |item| %> 
      <tr>
        <td id="description"><%= item.description %></td>

        <td>
        <form action="#" method="#">
          <input type="checkbox" name="checked" value="checked" >
          
          <!-- <input type="submit" value="Submit"> -->
        </form>

        </td>

        <td>
          <%= link_to edit_item_path(item) do %>
            <i class="fa fa-pencil ajax-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to item, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
      </tr>
<% end %>
   

app/views/items/edit.html.erb
<%= render 'ajax_form' %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.list.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>List:</strong>
  <%= @item.list.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<% if @item.list.nil? %>
	<%= link_to 'Back', items_path %>
<% else %>
	<%= link_to 'Back', @item.list %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get Organized With Listly</title>
  <%= stylesheet_link_tag  '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', '//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css',        'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
  	<div class="container-fluid">
			<div class="navbar-header">	
				<a class="navbar-brand" href="#">List.ly</a>
			</div>	
		</div>
	</nav>
 <br>

 <div class="row">
 	<div class="col-md-6 col-md-offset-3">

   <%= yield %>
  
  </div>
  <div class="col-md-3"></div>
 </div>

</body>
</html>

app/views/lists/_ajax_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  
<% end %>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<% @lists.each do |list| %> 
      <tr>
        <td id="name"><%= list.name %></td>
        



        <td>
          <%= link_to list_path(list) do %>
            <i class="fa fa-eye"></i>
          <% end %>
        </td>
        <td class="pencil-holder">
          <%= link_to edit_list_path(list) do %>
            <i class="fa fa-pencil ajax-edit" ></i>
          <% end %>
        </td>
        <td>
          <%= link_to list, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
      </tr>
<% end %>

app/views/lists/edit.html.erb
<%= render 'ajax_form' %>

app/views/lists/form.html.erb
<%= render 'ajax_form' %>

app/views/lists/index.html.erb
<button class="btn-lg btn-danger" id="new-button" type="button">
  <div id="new-text">Create New List</div>
  <div id="never-mind-text" style="display:none">Never Mind</div>
</button>
<!-- <button class="btn-lg btn-danger" id="new-list-button" type="button" style="display:none">Never Mind</button> -->


<!-- hidden -->
<div id="new-form" style="display:none">
    <%= render 'form' %>
  </div>

<!-- use count or length? -->
<% if ! @lists.empty? %>
  

<table class="note-pad table">
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th colspan="3"></th> -->
      <th>See List</th>
      <th>Change List Name</th>
      <th>Delete List</th>
    </tr>
  </thead>

  <tbody>
    <%= render 'list' %>
  </tbody>
</table>
<% end %>
<br>

<div class="result">


</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h2>  <%= @list.name %> </h2>

<button class="btn-lg btn-danger" id="new-button" type="button">
  <div id="new-text">Add Item</div>
  <div id="never-mind-text" style="display:none">Never Mind</div>
</button>

<div id="new-form" style="display:none">

  <%= render 'items/form' %>

</div>

<table class='note-pad table'>
	<tbody>
	
		<%= render 'items/list' %>

	 </tbody>
	</table>





<%= link_to 'Change List Name', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>